#!/usr/bin/env python

import rospy
from riptide_gazebo.depth_sensor_sim import DepthSensor

def main():
   rospy.init_node('depth_sensor_node')
   depth = DepthSensor()
   rospy.spin()

if __name__ == "__main__":
   main()