#!/usr/bin/env python

import rospy
from riptide_gazebo.thrust_converter import ThrustConverter

def main():
   rospy.init_node('thrust_converter_node')
   tc = ThrustConverter()
   rospy.spin()

if __name__ == "__main__":
   main()